# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3a38c55b45703d80f1c8adfb558044e8c69073f6c3ba42fe3e37aa4f10e35a1d995dbf370b394ac98fbd1f6eabe35f6b1e7e911ea282c88a63bdcc04c75eee2

test:
  secret_key_base: 1981038a13204ca52788e17421e7c76cff1222e345e6df71b274927fe9fb105612a10d3be34601a4e87c4b50078ef54b9f5ed6239cbd4f1824744418d7a4a322

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
